### ISSUE TITLE
Should we include user information?

### ISSUE THREAD

**Issue by rdb** [bible-technology/scripture-burrito#91] opened 2019-11-20 13:50 UTC
I apologise if this has been discussed before; I could not find an issue for it.

Currently the spec specifically refers to users who have produced/uploaded the burrito, by name and by unique identifier.  I am not really a fan of this, for several reasons, but willing to be convinced otherwise.

Firstly, including personally identifiable information may mean that burritos are affected by data protection regulations such as GDPR, which may place legal limits on the ability to transfer burritos to servers in other countries.  IANAL, so I do not know how far-reaching the implications are (and I might be completely wrong on this).

Secondly, from a purely conceptual level I am not sure that it should be considered in-scope for the burrito metadata to say something that is not descriptive of the contents but rather of the person who created it.  Including the name and version of the software that generated it is useful because it may say something meaningful about the contents thereof, but the identity of the person who did it does not.  (And when burritos are offered for wider distribution, people who publish burritos on behalf of their organisation may not even want their personal names attached.)

Thirdly, I can't see how it's *useful*.  The fact that identifiers are system-specific, and privacy considerations mean that user information cannot just be queried by an arbitrary party from a public API without the user's consent, effectively means that a system is likely storing this purely for its own consumption, but a system that needs this will likely already be storing its own event log accompanying the actual metadata.  But, this is purely my own speculation, so it would be valuable for others to weigh in.

**Comment by mvahowe** [comment] 2019-11-20 17:35
I can confirm that having the archivist name often turns out to be in DBL, for example to work out how things ended up the way they did. This works without user ids because there's only one DBL. Giving user ids may or not enable DBL to identify the user - it might well do so if the user is in the Registry. But, in all cases, it tells me that I can't assume org-x's John Smith is DBL's John Smith, and that's something.

For GDPR I'd have thought that the name of the user is more of the problem than a somewhat opaque user id (unless someone is using SS numbers as keys or something.)

We should probably make these fields optional though.

**Comment by rdb** [comment] 2019-11-22 11:11
Is it often the case in DBL's situation that the uploader may be a different person than the person who produced the bundle?  I'm wondering whether it might perhaps be sufficient for DBL to record the uploader name alongside the bundle based on their authentication credentials.

For the record, GDPR is quite broad when it determines the meaning of personal data; even including the hair colour of the burrito producer would already become tricky.  Identifiers fall under it because they indirectly refer to a personal identity and can be used to track that individual.  Article 4 is unambiguous about this (emphasis mine):
> ‘Personal data’ means any information relating to an identified or identifiable natural person (‘data subject’); an identifiable natural person is one who can be identified, **directly or indirectly**, in particular by reference to an identifier such as a name, an **identification number**, location data, an **online identifier** or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person.

This would mean that burritos do fall under data protection laws, and anyone processing burritos containing references to EU citizens and sharing them with third parties would have to abide by the stipulations of the GDPR, such as requiring explicit (and withdrawable) consent to share them with specifically enumerated third-party recipients of the data for specifically enumerated purposes.

This is not the responsibility of the SBWG but of whoever produces and processes burritos, so we could simply make these fields optional and not concern ourselves further with it, but these considerations may add a practical barrier to the usefulness of this field.

**Comment by mvahowe** [comment] 2019-11-22 11:17
We added a second user identifier because the project archivist may not be the person uploading to DBL. (The total number of users who have uploaded to DBL is just over 100, with the vast majority of entries being uploaded by less than 20 users - these figures are orders of magnitude lower than the number of archivists who have prepared projects now in DBL.)

I think it's good to flag GDPR but I agree that we should not make GDPR compliance a SB problem. In some cases, SBs may never be seen by anyone but the owner, in others they could potentially appear all over the place. So GDPR seems to me to be partly an ecosystem question rather than a data representation question. I would imagine that a DBL approach to this would be to extend the current "strip on export" mechanisms used to provide specific users with a suitable subset of information.

**Comment by mvahowe** [comment] 2020-02-20 12:13
I feel like we've settled this issue for now, the answer being something like "Yes, sometimes, optionally", so can we close this?

**Closed** 2020-02-27 16:08 UTC
Labels: Close Request, Policy
