### ISSUE TITLE
Conventions - we need some

### ISSUE THREAD

**Issue by mvahowe** [bible-technology/scripture-burrito#96] opened 2019-12-03 20:13 UTC
Conventions are the proposed mechanism for specifying burrito content. Without those we just have metadata in a vanilla container. We need to start fleshing out detail on the level of which files in which directories will be allowed/required.

scriptureText seems like the obvious place to start. I think we could start with the contents we would need for PA to be able to typeset a project based only on content contained in a PT-produced burrito.

We also need a plan for validating conventions. I had been intending to attempt this using Schematron. In the brave new world of JSON that isn't an option.  There's always

https://www.npmjs.com/package/jsontron

but this is so obscure that something we made up between us might end up with more users.

**Comment by jag3773** [comment] 2019-12-04 21:53
For anyone else looking for more context, I found this a helpful overview of what the problem is: https://stackoverflow.com/questions/28629107/json-is-there-an-equivalent-of-schematron-for-json-and-json-schema-that-is-a

**Comment by jag3773** [comment] 2020-11-05 16:34
Hooks built into the libraries for validating content (by mimetype) would be helpful.

Other than that, metadata validation beyond what jsonschema supports (like validating that a prefix used in a document is declared up above) will be addressed as they come up and we'll use our example libraries to validate such things. See #223.

**Comment by jtauber** [comment] 2020-12-10 14:48
Other than "Hooks built into the libraries for validating content (by mimetype) would be helpful." what, if anything, needs to be done to declare victory on this issue?

**Comment by jag3773** [comment] 2020-12-14 18:34
Our conversation suggested that we'll close this one as soon as the hooks are in place. Other specific issues will be documented and added as they come (like the #223 issue).

**Closed** 2021-01-07 16:38 UTC
Labels: Defining Feature or Fix
