### ISSUE TITLE
Document Bible Story Gloss

### ISSUE THREAD

**Issue by mvahowe** [bible-technology/scripture-burrito#55] opened 2019-08-20 17:33 UTC
I've done some more work on this, including adding references to the metadata for the 50 stories. I've also set up a documentation page with the same format as the other flavors.

@jag3773 Could you fill in some more under "status" in particular?

**Comment by jag3773** [comment] 2019-08-22 12:42
Duplicate of #14

**Closed by jag3773** 2019-08-22 12:42 UTC
Labels: duplicate
